apiVersion: v1
kind: Service
metadata:
  name: myjavaapp
  labels:
    app: myjavaapp
spec:
   type: NodePort
   ports:
   - port: 80
     nodeport: 30001
     protocol: TCP
   selector:
     app: myjavaapp
